version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - gem install berkshelf -v 5.1.0
  build:
    commands:
      - echo Entered the build phase...
      - export REVISION_ID=`echo $REVISION | sed 's/\//-/g'`
      - berks package mh-opsworks-recipes-${REVISION_ID}.tar.gz
artifacts:
  files:
    - mh-opsworks-recipes-${REVISION_ID}.tar.gz
  discard-paths: yes
  secondary-artifacts:
    secondary:
      files:
      - mh-opsworks-recipes-${REVISION_ID}.tar.gz
      discard-paths: yes
