AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cookbook and app packager for mh-opsworks

Parameters:
  BuildBucketName:
    Type: String
    Default: ""
  DefaultRevision:
    Type: String
    Default: develop
  BuildSpec:
    Type: String

Resources:

  MhOpsworksBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-service-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      - arn:aws:iam::aws:policy/AWSLambdaExecute

  BuilderFunction:
    Type: AWS::Serverless::Function
    DependsOn: MhOpsworksBuilderRole
    Properties:
      Handler: builder.handler
      Runtime: python3.6
      Role: !GetAtt [MhOpsworksBuilderRole, Arn]
      FunctionName: !Sub "${AWS::StackName}"
      Environment:
        Variables:
          STACK_NAME: !Sub "${AWS::StackName}"
          COOKBOOK_BUILD_PROJECT: !Sub "cookbook-${AWS::StackName}"
          OPENCAST_BUILD_PROJECT: !Sub "opencast-${AWS::StackName}"
      Events:
        BuildCookbook:
          Type: Api
          Properties:
            Path: /buildcookbook
            Method: post
      Tags:
        Project: MH
        OU: DE

  CookbookBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: MhOpsworksBuilderRole
    Properties:
      Name: !Sub "cookbook-${AWS::StackName}"
      TimeoutInMinutes: 5
      Description: Prepackage mh-opsworks-recipes cookbook
      Source:
        Location: https://github.com/harvard-dce/mh-opsworks-recipes.git
        Type: GITHUB
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: aws/codebuild/ruby:2.2.5
        EnvironmentVariables:
          - Name: REVISION
            Value: !Ref DefaultRevision
      Artifacts:
        Location: !Sub "{AWS::StackName}"
        Type: S3
        Name: cookbooks
      ServiceRole: !GetAtt [MhOpsworksBuilderRole, Arn]
      Tags:
        - Key: Project
          Value: MH
        - Key: OU
          Value: DE

  OpencastBuildsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-opencast"

  OpencastBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: MhOpsworksBuilderRole
    Properties:
      Name: !Sub "opencast-${AWS::StackName}"
      TimeoutInMinutes: 30
      BadgeEnabled: true
      Source:
        Location: "https://bitbucket.org/hudcede/matterhorn-dce-fork.git"
        Type: BITBUCKET
        BuildSpec: !Ref BuildSpec
        Auth:
          Type: OAUTH
      Environment:
        ComputeType: BUILD_GENERAL1_LARGE
        Type: LINUX_CONTAINER
        Image: aws/codebuild/java:openjdk-8
        EnvironmentVariables:
        - Name: REVISION
          Value: !Ref DefaultRevision
      Artifacts:
        Type: S3
        Location: !Sub "${AWS::StackName}-opencast"
      ServiceRole: !GetAtt [MhOpsworksBuilderRole, Arn]
      Tags:
      - Key: Project
        Value: MH
      - Key: OU
        Value: DE
